apps/apps/urls.py
from django.contrib import admin
from django.urls import path, include

import theme.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', theme.views.home, name='home'),
    path('books_simple/', include('books_simple.urls')),
    path('books_pc_formset/', include('books_pc_formset.urls')),
    path('books_pc_formset2/', include('books_pc_formset2.urls')),
    path('books_pc_multi_view/', include('books_pc_multi_view.urls')),
    path('books_pc_multi_view2/', include('books_pc_multi_view2.urls')),
]

apps/books_pc_formset/urls.py
from django.urls import path

from . import views

app_name = 'books_pc_formset'

urlpatterns = [
    path('', views.home, name='home'),
    path('new/', views.book_create, name='book_new'),
    path('edit/<int:pk>/', views.book_update, name='book_edit'),
    path('delete/<int:pk>/', views.book_delete, name='book_delete'),
]

apps/books_pc_formset2/urls.py
from django.urls import path

from . import views

app_name = 'books_pc_formset2'

urlpatterns = [
    path('', views.home, name='home'),

    path('person_new', views.person_create, name='person_new'),
    path('person_edit/<int:pk>', views.person_update, name='person_edit'),
    path('person_delete/<int:pk>', views.person_delete, name='person_delete'),

    path('book_new', views.book_create, name='book_new'),
    path('book_edit/<int:pk>', views.book_update, name='book_edit'),
    path('book_delete/<int:pk>', views.book_delete, name='book_delete'),
]

apps/books_pc_multi_view/urls.py
from django.urls import path

from . import views

app_name = 'books_pc_multi_view'

urlpatterns = [
    path('', views.home, name='home'),

    path('book_view/<int:pk>/', views.book_view, name='book_view'),
    path('book_new', views.book_create, name='book_new'),
    path('book_edit/<int:pk>/', views.book_update, name='book_edit'),
    path('book_delete/<int:pk>/', views.book_delete, name='book_delete'),

    path('review_new/<int:parent_pk>/', views.review_create, name='review_new'),
    path('review_edit/<int:pk>/', views.review_update, name='review_edit'),
    path('review_delete/<int:pk>/', views.review_delete, name='review_delete'),
]

apps/books_simple/urls.py
from django.urls import path

from . import views

app_name = 'books_simple'

urlpatterns = [
    path('', views.home, name='home'),
    path('new/', views.book_create, name='book_new'),
    path('edit/<int:pk>/', views.book_update, name='book_edit'),
    path('delete/<int:pk>/', views.book_delete, name='book_delete'),
]

apps/theme/models.py
from django.db import models

# Create your models here.

apps/theme/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

apps/theme/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django CRUD: {% block title %}Welcome{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" media="all" rel="stylesheet" />
</head>

<body>
<div id="wrapper">
    <h1><a href="{% url 'home' %}">Django CRUD Parent/Child Edition</a></h1>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div><!-- wrapper -->
</body>
</html>

apps/theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<ul>
<li><a href="{% url 'books_simple:home' %}">Simple CRUD</a></li>
<li><a href="{% url 'books_pc_formset:home' %}">Parent/Child using Formset</a></li>
<li><a href="{% url 'books_pc_formset2:home' %}">Parent/Child using Formset and Foreign Key</a></li>
<li><a href="{% url 'books_pc_multi_view:home' %}">Parent/Child using multiple views</a></li>
<li><a href="{% url 'books_pc_multi_view2:home' %}">Parent/Child using multiple views and Foreign Key</a></li>
</ul>

You can also access Django built-in <a href="/admin/">Admin interface</a>, you would need to
create a user using the following command:

<pre>./manage.py  createsuperuser</pre>
{% endblock %}