apps/apps/urls.py
from django.contrib import admin
from django.urls import path, include

import theme.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', theme.views.home, name='home'),
    path('books_simple/', include('books_simple.urls')),
    path('books_pc_formset/', include('books_pc_formset.urls')),
    path('books_pc_formset2/', include('books_pc_formset2.urls')),
    path('books_pc_multi_view/', include('books_pc_multi_view.urls')),
    path('books_pc_multi_view2/', include('books_pc_multi_view2.urls')),
]

apps/books_pc_multi_view2/urls.py
from django.urls import path

from . import views

app_name = 'books_pc_multi_view2'

urlpatterns = [
    path('', views.home, name='home'),

    path('person_new', views.person_create, name='person_new'),
    path('person_edit/<int:pk>/', views.person_update, name='person_edit'),
    path('person_delete/<int:pk>/', views.person_delete, name='person_delete'),

    path('book_view/<int:pk>/', views.book_view, name='book_view'),
    path('book_new', views.book_create, name='book_new'),
    path('book_edit/<int:pk>/', views.book_update, name='book_edit'),
    path('book_delete/<int:pk>/', views.book_delete, name='book_delete'),

    path('review_new/<int:parent_pk>/', views.review_create, name='review_new'),
    path('review_edit/<int:pk>/', views.review_update, name='review_edit'),
    path('review_delete/<int:pk>/', views.review_delete, name='review_delete'),
]

apps/books_pc_multi_view2/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name


class Review(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    review = models.TextField()

    def __str__(self):
        return "Review from: " + self.person.name

apps/books_pc_multi_view2/forms.py
from django.forms import ModelForm

from .models import Person, Book, Review

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'email']

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['person', 'review']

apps/books_pc_multi_view2/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Person, Book, Review
from .forms import PersonForm, BookForm, ReviewForm


# ========== Home =========

def home(request, template_name='books_pc_multi_view2/home.html'):
    books = Book.objects.all()
    persons = Person.objects.all()
    ctx = {
        'books': books,
        'persons': persons,
    }
    return render(request, template_name, ctx)
    

# ========== Book CRUD =========

def book_view(request, pk, template_name='books_pc_multi_view2/book_view.html'):
    book= get_object_or_404(Book, pk=pk)
    reviews = Review.objects.filter(book=book)
    ctx = {
        'book': book,
        'reviews': reviews,
    }
    return render(request, template_name, ctx)

def book_create(request, template_name='books_pc_multi_view2/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view2:home')
    ctx = {
        'form': form,
    }
    return render(request, template_name, ctx)

def book_update(request, pk, template_name='books_pc_multi_view2/book_form.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view2:home')
    ctx = {
        'form': form,
        'book': book,
    }
    return render(request, template_name, ctx)

def book_delete(request, pk, template_name='books_pc_multi_view2/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('books_pc_multi_view2:home')
    ctx = {
        'object': book,
        'book': book,
    }
    return render(request, template_name, ctx)


# ========== Review CRUD =========

def review_create(request, parent_pk, template_name='books_pc_multi_view2/review_form.html'):
    book = get_object_or_404(Book, pk=parent_pk)
    form = ReviewForm(request.POST or None)
    if form.is_valid():
        review = form.save(commit=False)
        review.book = book
        review.save()
        return redirect('books_pc_multi_view2:book_view', parent_pk)
    ctx = {
        'form': form,
        'book': book,
    }
    return render(request, template_name, ctx)

def review_update(request, pk, template_name='books_pc_multi_view2/review_form.html'):
    review = get_object_or_404(Review, pk=pk)
    parent_pk = review.book.pk
    form = ReviewForm(request.POST or None, instance=review)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view2:book_view', parent_pk)
    ctx = {
        'form': form,
        'book': review.book,
    }
    return render(request, template_name, ctx)

def review_delete(request, pk, template_name='books_pc_multi_view2/review_confirm_delete.html'):
    review = get_object_or_404(Review, pk=pk)    
    parent_pk = review.book.pk
    if request.method=='POST':
        review.delete()
        return redirect('books_pc_multi_view2:book_view', parent_pk)
    ctx = {
        'object': review,
        'book': review.book,
    }
    return render(request, template_name, ctx)


# ============ Person CRUD ===============

def person_create(request, template_name='books_pc_multi_view2/person_form.html'):
    form = PersonForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view2:home')
    ctx = {
        'form': form,
    }
    return render(request, template_name, ctx)

def person_update(request, pk, template_name='books_pc_multi_view2/person_form.html'):
    person = get_object_or_404(Person, pk=pk)
    form = PersonForm(request.POST or None, instance=person)
    if form.is_valid():
        form.save()
        return redirect('books_pc_multi_view2:home')
    ctx = {
        'form': form,
    }
    return render(request, template_name, ctx)

def person_delete(request, pk, template_name='books_pc_multi_view2/person_confirm_delete.html'):
    person= get_object_or_404(Person, pk=pk)    
    if request.method=='POST':
        person.delete()
        return redirect('books_pc_multi_view2:home')
    ctx = {
        'person': person,
    }
    return render(request, template_name, ctx)

apps/books_pc_multi_view2/templates/books_pc_multi_view2/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_multi_view2/nav.html" with book=book title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/book_form.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view2/nav.html" with book=book title="Edit" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/book_view.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view2/nav.html" with book=book title="View" %}

Pages: {{ book.pages }}

<h2>Reviews</h2>
<ul>
    {% for review in reviews %}
    <li>
        {{ review.person }}<br>
        {{ review.review|linebreaks }}
        <br>
        <a href="{% url 'books_pc_multi_view2:review_edit' review.id %}">edit</a>
        <a href="{% url 'books_pc_multi_view2:review_delete' review.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_multi_view2:review_new' book.id %}">New Review</a>
{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/home.html
{% extends "base.html" %}

{% block title %}Book List{% endblock %}

{% block content %}
{% include "books_pc_multi_view2/nav.html" %}

Books Parent/Child with Multi View and Foreign Key

<h2>People</h2>
<ul>
    {% for person in persons %}
    <li>{{ person.name }}  ({{ person.email }})
    <a href="{% url 'books_pc_multi_view2:person_edit' person.id %}">edit</a>
    <a href="{% url 'books_pc_multi_view2:person_delete' person.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_multi_view2:person_new' %}">New</a>


<h2>Books</h2>
<ul>
    {% for book in books %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_pc_multi_view2:book_view' book.id %}">view</a>
    <a href="{% url 'books_pc_multi_view2:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_pc_multi_view2:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_pc_multi_view2:book_new' %}">New</a>
{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/nav.html
<h2>
<a href="{% url 'books_pc_multi_view2:home' %}">Application Home</a>
{% if book %}
&gt; <a href="{% url 'books_pc_multi_view2:book_view' book.id %}">{{ book.name }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

apps/books_pc_multi_view2/templates/books_pc_multi_view2/person_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_multi_view2/nav.html" with person=person title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ person }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/person_form.html
{% extends "base.html" %}

{% block content %}
{% include "books_pc_multi_view2/nav.html" with person=person title="Edit Person" %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/review_confirm_delete.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view2/nav.html" with book=book title="Delete Review" %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

apps/books_pc_multi_view2/templates/books_pc_multi_view2/review_form.html
{% extends "base.html" %}


{% block content %}
{% include "books_pc_multi_view2/nav.html" with book=book title="Edit Review" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}